const express = require("express");
const { v4: uuidv4 } = require("uuid");
const app = express();
const PORT = process.env.PORT || 5000;

app.get("/", (req, res) => {
  res.json({
    coffee: [
      { id: uuidv4(), name: "espresso", price: "2.10", img: "url" },
      { name: "black coffee", price: "2,10", img: "url" },

      { id: uuidv4(), name: "cappuccino", price: "2,40", img: "url" },
      { id: uuidv4(), name: "latte", price: "2,40", img: "url" },
      { id: uuidv4(), name: "espresso macchiato", price: "2,40", img: "url" },
      { id: uuidv4(), name: "latte macchiaro", price: "2,80", img: "url" },
      { id: uuidv4(), name: "flat white", price: "3.50", img: "url" },
      {
        id: uuidv4(),
        name: "dubbele latte/cappuccino",
        price: "3,70",
        img: "url",
      },
      { id: uuidv4(), name: "dubbele espresso", price: "3,20", img: "url" },
      { id: uuidv4(), name: "irish coffee", price: "6,10", img: "url" },
      { id: uuidv4(), name: "hot chocolate", price: "2,60", img: "url" },
      { id: uuidv4(), name: "glass milk", price: "2", img: "url" },
      { id: uuidv4(), name: "soj/oat milk", price: "0,40", img: "url" },
      { id: uuidv4(), name: "whipped cream", price: "0,50", img: "url" },
      { id: uuidv4(), name: "syrup", price: "0,40", img: "url" },
    ],
    tea: [
      { id: uuidv4(), name: "tea", price: "2.10", img: "url" },
      { id: uuidv4(), name: "  fresh mint tea", price: "2.50", img: "url" },
      { id: uuidv4(), name: "fresh ginger tea", price: "2.50", img: "url" },
      { id: uuidv4(), name: "ginger mint tea", price: "2.80", img: "url" },
    ],
    sweet: [
      { id: uuidv4(), name: "homemade cake", price: "3.50", img: "url" },
      { id: uuidv4(), name: "banana", price: "1", img: "url" },
      { id: uuidv4(), name: "whipped cream", price: "0.50", img: "url" },
      {
        id: uuidv4(),
        name: "home made granola with honey with cinnamon",
        price: "2.60",
        img: "url",
      },
      {
        id: uuidv4(),
        name: "banana honey and cinnamon",
        price: "3.20",
        img: "url",
      },
      {
        id: uuidv4(),
        name: "tuti: homemade granola banana honey with cinnamon ",
        price: "",
        img: "url",
      },
    ],
    tosti: [
      { id: uuidv4(), name: "cheese", price: "3", img: "url" },
      { id: uuidv4(), name: "cheese and ham", price: "3.60", img: "url" },
      { id: uuidv4(), name: "pikant", price: "", img: "url" },
    ],
    sandwich: [
      {
        id: uuidv4(),
        name: "dutch cheese with tomato cucumber and rocket (V)",
        price: "3.50",
        img: "url",
      },
      {
        id: uuidv4(),
        name: "hummus tomato cucumber rocket",
        price: "3.50",
        img: "url",
      },
      {
        id: uuidv4(),
        name: "mozzarella tomato pesto and rocket",
        price: "5",
        img: "url",
      },
      { id: uuidv4(), name: "b.l.t", price: "5", img: "url" },
      { id: uuidv4(), name: "sandwich of the week", price: "4.50", img: "url" },
      { id: uuidv4(), name: "soup of the week", price: "5.50", img: "url" },
    ],
    bites: [
      { id: uuidv4(), name: "hot nacho's", price: "8", img: "url" },
      { id: uuidv4(), name: "bitter balls (7 pcs)", price: "5.90", img: "url" },
      {
        id: uuidv4(),
        name: "mini cheese souflles (7 pcs)",
        price: "5.90",
        img: "url",
      },
      {
        id: uuidv4(),
        name: "cheese sticks (7 pcs)",
        price: "5,90",
        img: "url",
      },
      { id: uuidv4(), name: "chicken nuggets (7 pcs)", price: "", img: "url" },
      {
        id: uuidv4(),
        name: "mix snacks small (12 pcs)",
        price: "10",
        img: "url",
      },
      { id: uuidv4(), name: "chicken nuggets (7 pcs)", price: "", img: "url" },
      {
        id: uuidv4(),
        name: "mix snacks big (20 pcs)",
        price: "16",
        img: "url",
      },
      { id: uuidv4(), name: "chicken nuggets (7 pcs)", price: "", img: "url" },
      {
        id: uuidv4(),
        name: "mix snacks small (12 pcs)",
        price: "10",
        img: "url",
      },
      { id: uuidv4(), name: "mixed nuts", price: "2.80", img: "url" },
      {
        id: uuidv4(),
        name: "bread with aioli and hummus",
        price: "4",
        img: "url",
      },
      { id: uuidv4(), name: "nacho's with salsa", price: "3,20", img: "url" },
      {
        id: uuidv4(),
        name: "nacho's with guacamole",
        price: "3.80",
        img: "url",
      },
    ],
    soda: [
      { id: uuidv4(), name: "cola", price: "2.30", img: "url" },
      { id: uuidv4(), name: "cola light", price: "2.30", img: "url" },
      { id: uuidv4(), name: "sprite", price: "2.30", img: "url" },
      { id: uuidv4(), name: "fanta", price: "2.30", img: "url" },
      { id: uuidv4(), name: "fanta cassis", price: "2.30", img: "url" },
      { id: uuidv4(), name: "tonic", price: "2.30", img: "url" },
      { id: uuidv4(), name: "bitter lemon", price: "2.30", img: "url" },
      { id: uuidv4(), name: "ginger ale", price: "2.30", img: "url" },
      { id: uuidv4(), name: "sparkling water ", price: "2.30", img: "url" },
      { id: uuidv4(), name: "ice tea green", price: "2.30", img: "url" },
      { id: uuidv4(), name: "ice tea peach", price: "2.30", img: "url" },
    ],
    extraFris: [
      { id: uuidv4(), name: "elderflower(belvoir)", price: "3.50", img: "url" },
      { id: uuidv4(), name: "ginger beer(belvoir)", price: "3.50", img: "url" },
      { id: uuidv4(), name: "bionade(elderberry)", price: "3.50", img: "url" },
      {
        id: uuidv4(),
        name: "bionade(orange-ginger)",
        price: "3.50",
        img: "url",
      },
      { id: uuidv4(), name: "bionade(lemon)", price: "3.50", img: "url" },
      {
        id: uuidv4(),
        name: "club mate(with caffeine)",
        price: "3.50",
        img: "url",
      },
      { id: uuidv4(), name: "apple juice(flevo)", price: "2.30", img: "url" },
      { id: uuidv4(), name: "pear juice (looza)", price: "2.40", img: "url" },
      { id: uuidv4(), name: "tomato juice(looza)", price: "2.40", img: "url" },
      { id: uuidv4(), name: "fresh orange juice", price: "3.20", img: "url" },
    ],
    beerOnDraft: [
      { id: uuidv4(), name: "grolsch pils (s)", price: "2.20", img: "url" },
      { id: uuidv4(), name: "grolsch (m)", price: "2.40", img: "url" },
      { id: uuidv4(), name: "grolsch (l)", price: "4.60", img: "url" },
      { id: uuidv4(), name: "pitcher grolsch", price: "14", img: "url" },
      { id: uuidv4(), name: "grolsch weizen (5.1%)", price: "4", img: "url" },
      { id: uuidv4(), name: "grimbergen (changing)", price: "4", img: "url" },
      { id: uuidv4(), name: "la chouffe (8%)", price: "4.20", img: "url" },
      {
        id: uuidv4(),
        name: "grolsch (changeing draft)",
        price: "4",
        img: "url",
      },
      { id: uuidv4(), name: "grolsch (proeverih)", price: "4.50", img: "url" },
      { id: uuidv4(), name: "local changing tap ", price: "4.50", img: "url" },
      { id: uuidv4(), name: "kunst kater", price: "3.20", img: "url" },
    ],
    beerOnBottle: [
      { id: uuidv4(), name: "vedett extra blond(5.2%)", price: "", img: "url" },
      { id: uuidv4(), name: "duvel(8.5%)", price: "4.80", img: "url" },
      { id: uuidv4(), name: "vedettm i.p.a(5.5%)", price: "4.30", img: "url" },
      { id: uuidv4(), name: "oedipus(changing)", price: "4.50", img: "url" },
      {
        id: uuidv4(),
        name: "browerij`t ij ijwit(6.5%)",
        price: "4.50",
        img: "url",
      },
      {
        id: uuidv4(),
        name: "browerij`t ij zatte(8%)",
        price: "4.50",
        img: "url",
      },
      { id: uuidv4(), name: "changing beer bottle", price: "4", img: "url" },
      {
        id: uuidv4(),
        name: "mort subite kriek(4%)",
        price: "3.50",
        img: "url",
      },
      { id: uuidv4(), name: "grolsch radler(2.5%)", price: "3", img: "url" },
      { id: uuidv4(), name: "grolsch 0 %", price: "2.30", img: "url" },
      { id: uuidv4(), name: "grolsch weizen 0 %", price: "3.50", img: "url" },
      { id: uuidv4(), name: "magners cider", price: "4.80", img: "url" },
    ],
    wine: [
      { id: uuidv4(), name: "red", price: "3.50", img: "url" },
      { id: uuidv4(), name: "white", price: "3.50", img: "url" },
      { id: uuidv4(), name: "rose", price: "3.50", img: "url" },
      { id: uuidv4(), name: "red bottle", price: "18.50", img: "url" },
      { id: uuidv4(), name: "white bottle", price: "18.50", img: "url" },
      { id: uuidv4(), name: "rose bottle", price: "18.50", img: "url" },
      { id: uuidv4(), name: "dow's port", price: "3.50", img: "url" },
      { id: uuidv4(), name: "martini rosso", price: "3.50", img: "url" },
      { id: uuidv4(), name: "martini blanco", price: "3.50", img: "url" },
    ],
    whiskey: [
      { id: uuidv4(), name: "jameson", price: "4.50", img: "url" },
      { id: uuidv4(), name: "four roses", price: "4.50", img: "url" },
      { id: uuidv4(), name: "jack daniels", price: "4.50", img: "url" },
      {
        id: uuidv4(),
        name: "glenfiddich single malt 10 yr",
        price: "6",
        img: "url",
      },
      {
        id: uuidv4(),
        name: "laphroaig single malt 10 yr",
        price: "6.50",
        img: "url",
      },
      { id: uuidv4(), name: "joseph guy", price: "4.50", img: "url" },
      { id: uuidv4(), name: "calvados", price: "4.50", img: "url" },
      { id: uuidv4(), name: "remy martin vsop", price: "6.50", img: "url" },
    ],
    liqueur: [
      { id: uuidv4(), name: "amaretto", price: "4.50", img: "url" },
      { id: uuidv4(), name: "baileys", price: "4.50", img: "url" },
      { id: uuidv4(), name: "cointreau", price: "4.50", img: "url" },
      { id: uuidv4(), name: "drambuie", price: "4.50", img: "url" },
      { id: uuidv4(), name: "liqueur 43", price: "4.50", img: "url" },
      { id: uuidv4(), name: "grand marnier", price: "4.50", img: "url" },
      { id: uuidv4(), name: "malibu", price: "4.50", img: "url" },
      { id: uuidv4(), name: "tia maria", price: "4.50", img: "url" },
      { id: uuidv4(), name: "sambuca", price: "4.50", img: "url" },
      { id: uuidv4(), name: "southern comfort", price: "4.50", img: "url" },
      { id: uuidv4(), name: "st.germain", price: "4.50", img: "url" },
      { id: uuidv4(), name: "frangelico", price: "4.50", img: "url" },
    ],
    distilled: [
      { id: uuidv4(), name: "bombay sapphire gin", price: "4.50", img: "url" },
      { id: uuidv4(), name: "tanqueray gin", price: "4.50", img: "url" },
      { id: uuidv4(), name: "wodka", price: "4.50", img: "url" },
      { id: uuidv4(), name: "verhoeven jonge jenever", price: "3", img: "url" },
      { id: uuidv4(), name: "bokma oude jenever", price: "3", img: "url" },
      { id: uuidv4(), name: "bols vieux", price: "3", img: "url" },
      { id: uuidv4(), name: "sonnema beenburg", price: "3", img: "url" },
      { id: uuidv4(), name: "bessenjenever", price: "3", img: "url" },
      { id: uuidv4(), name: "apfelkorn", price: "3", img: "url" },
      { id: uuidv4(), name: "campari", price: "3.50", img: "url" },
      { id: uuidv4(), name: "julia grappa", price: "3.50", img: "url" },
      { id: uuidv4(), name: "jagermeister", price: "3", img: "url" },
      { id: uuidv4(), name: "bacardi superior", price: "4.50", img: "url" },
      {
        id: uuidv4(),
        name: "pampero anejo especial",
        price: "4.80",
        img: "url",
      },
      { id: uuidv4(), name: "tequilla gold", price: "4.50", img: "url" },
      { id: uuidv4(), name: "tequilla silver", price: "4.50", img: "url" },
      { id: uuidv4(), name: "pernod", price: "4.50", img: "url" },
      { id: uuidv4(), name: "salmari", price: "3", img: "url" },
    ],
  });
});

app.listen(PORT);
